# Generated by Django 6.0.1 on 2026-02-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='老师姓名')),
                ('teacher_id', models.CharField(max_length=20, unique=True, verbose_name='工号')),
                ('subject', models.CharField(max_length=50, verbose_name='教授科目')),
            ],
            options={
                'verbose_name': '老师信息',
                'verbose_name_plural': '老师信息',
            },
        ),
    ]
