[pytest]
# 告诉 pytest，Django 的配置文件在哪里
DJANGO_SETTINGS_MODULE = my_lms.settings

# 匹配测试文件的规则
python_files = test_*.py

# 3. 【重点】解决控制台中文显示为 Unicode 编码的问题
# 这个配置项名字很长，是 Pytest 官方的一个梗，但它真的有用！
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True

# 4. 注册自定义 Marker，消除 "PytestUnknownMarkWarning" 警告
markers =
    django_db: mark test to use database
    smoke: mark test as a smoke test